# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_livro', models.CharField(max_length=200)),
                ('autor_livro', models.CharField(max_length=200)),
                ('editora_livro', models.CharField(max_length=200)),
                ('categoria_livro', models.CharField(max_length=200)),
            ],
        ),
    ]
